/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author jesus
 */
public class GUIMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIMain.class.getName());
    private static final String PROJECT_NAME = "Electronic Components Project";
    private static final String PROJECT_VERSION = "1.0";
    private static final String TEAM_NAMES = "Juan Bocanegra, David Perez, Daniel Hoyos";

    /**
     * Creates new form GUIMain
     */
    public GUIMain() {
        initComponents();
        configureMenu();
        setTitle("Electronic Components Project");
        setLocationRelativeTo(null);
    }

    private void configureMenu() {
        setJMenuBar(buildMenuBar());
    }

    private javax.swing.JMenuBar buildMenuBar() {
        javax.swing.JMenuBar menuBar = new javax.swing.JMenuBar();

        javax.swing.JMenu operationsMenu = new javax.swing.JMenu("Operaciones");
        operationsMenu.add(createMenuItem("Adicionar", () -> new GUIAdicionar().setVisible(true)));
        operationsMenu.add(createMenuItem("Listar", () -> new GUIListComponent().setVisible(true)));
        operationsMenu.add(createMenuItem("Consultar", () -> new GUIConsultar().setVisible(true)));
        operationsMenu.add(createMenuItem("Eliminar", () -> new GUIEliminar().setVisible(true)));

        javax.swing.JMenu helpMenu = new javax.swing.JMenu("Ayuda");
        helpMenu.add(createMenuItem("Acerca de...", this::showAboutDialog));

        menuBar.add(operationsMenu);
        menuBar.add(helpMenu);

        return menuBar;
    }

    private javax.swing.JMenuItem createMenuItem(String text, Runnable action) {
        javax.swing.JMenuItem item = new javax.swing.JMenuItem(text);
        item.addActionListener(event -> action.run());
        return item;
    }

    private void showAboutDialog() {
        String message = PROJECT_NAME
                + "\nVersion: " + PROJECT_VERSION
                + "\nIntegrantes: " + TEAM_NAMES;
        javax.swing.JOptionPane.showMessageDialog(this, message, "Acerca de...", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
